import { ICategory } from "../models/Category";
import { Backend } from "@n/adira.core.ts";
import { ErrorResponse } from "../types";
declare const getCategories: Backend.ExecuteGET<ICategory>;
declare const createCategory: Backend.ExecutePOST<ICategory>;
declare const updateCategory: Backend.ExecutePATCH<ICategory>;
declare const deleteCategory: Backend.ExecuteDELETE<ICategory>;
export type GetCategoriesFn = typeof getCategories;
export type CreateCategoryFn = typeof createCategory;
export type UpdateCategoryFn = typeof updateCategory;
export type DeleteCategoryFn = typeof deleteCategory;
