import { ICategory } from "../models/Category";
import { Backend } from "@n/adira.core.ts";
import { ErrorResponse } from "../types";
declare const getCategories: Backend.ExecuteGET<ICategory, {
    _id: import("@n/adira.core.ts").ObjectIdLike;
    name: string;
    description: string;
    slug: string;
    parentCategory: import("@n/adira.core.ts").CleanRef<ICategory> | null;
    createdBy: import("@n/adira.core.ts").CleanRef<import("../models/User").IUser> | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date | undefined;
}>;
declare const createCategory: Backend.ExecutePOST<ICategory, {
    _id: import("@n/adira.core.ts").ObjectIdLike;
    name: string;
    description: string;
    slug: string;
    parentCategory: import("@n/adira.core.ts").CleanRef<ICategory> | null;
    createdBy: import("@n/adira.core.ts").CleanRef<import("../models/User").IUser> | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date | undefined;
}>;
declare const updateCategory: Backend.ExecutePATCH<ICategory, {
    _id: import("@n/adira.core.ts").ObjectIdLike;
    name: string;
    description: string;
    slug: string;
    parentCategory: import("@n/adira.core.ts").CleanRef<ICategory> | null;
    createdBy: import("@n/adira.core.ts").CleanRef<import("../models/User").IUser> | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date | undefined;
}>;
declare const deleteCategory: Backend.ExecuteDELETE<ICategory, {
    _id: import("@n/adira.core.ts").ObjectIdLike;
    name: string;
    description: string;
    slug: string;
    parentCategory: import("@n/adira.core.ts").CleanRef<ICategory> | null;
    createdBy: import("@n/adira.core.ts").CleanRef<import("../models/User").IUser> | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date | undefined;
}>;
export type GetCategoriesFn = typeof getCategories;
export type CreateCategoryFn = typeof createCategory;
export type UpdateCategoryFn = typeof updateCategory;
export type DeleteCategoryFn = typeof deleteCategory;
