import { IOrder } from "../models/Order";
import { Backend } from "@n/adira.core.ts";
import { ErrorResponse } from "../types";
declare const getOrders: Backend.ExecuteGET<IOrder>;
declare const createOrder: Backend.ExecutePOST<IOrder>;
declare const updateOrder: Backend.ExecutePATCH<IOrder>;
declare const deleteOrder: Backend.ExecuteDELETE<IOrder>;
export type GetOrdersFn = typeof getOrders;
export type CreateOrderFn = typeof createOrder;
export type UpdateOrderFn = typeof updateOrder;
export type DeleteOrderFn = typeof deleteOrder;
