import { IProduct } from "../models/Product";
import { Backend } from "@n/adira.core.ts";
import { ErrorResponse } from "../types";
declare const getProducts: Backend.ExecuteGET<IProduct>;
declare const createProduct: Backend.ExecutePOST<IProduct>;
declare const updateProduct: Backend.ExecutePATCH<IProduct>;
declare const deleteProduct: Backend.ExecuteDELETE<IProduct>;
export type GetProductsFn = typeof getProducts;
export type CreateProductFn = typeof createProduct;
export type UpdateProductFn = typeof updateProduct;
export type DeleteProductFn = typeof deleteProduct;
