import { IUser } from "../models/User";
import { Backend } from "@n/adira.core.ts";
import { ErrorResponse } from "../types";
declare const getUsers: Backend.ExecuteGET<IUser>;
declare const createUser: Backend.ExecutePOST<IUser>;
declare const updateUser: Backend.ExecutePATCH<IUser>;
declare const deleteUser: Backend.ExecuteDELETE<IUser>;
export type GetUsersFn = typeof getUsers;
export type CreateUserFn = typeof createUser;
export type UpdateUserFn = typeof updateUser;
export type DeleteUserFn = typeof deleteUser;
